name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/upload-artifact@v4
    - name: Set up JDK 17
      uses: actions/upload-artifact@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LedgerSearch-APK
        path: app/build/outputs/apk/debug/app-debug.apk
